[package]
name = "supernaut"
version.workspace = true
edition.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
havoc-ipc.workspace = true
havoc-core.workspace = true
havoc-transport.workspace = true
supernaut-tui.workspace = true
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "io-std", "io-util", "time", "sync"] }
clap = { version = "4.6.6", features = ["derive"] }
